### ISSUE TITLE
Formato de impressão

### ISSUE THREAD

**Issue by garotadpi** [acessibilidade/toolkit#1]
Oi Marcelo! Sugiro na versão pdf colocar alguma informação de tamanho de página. O formato é uma carta por A4?

**Comment by msales78** [comment]
Olá Fernanda! No projeto que fiz o boneco, consegui deixar 4 cartas por folha A4, mas sei que talvez esse formato não seja a melhor opção pra uma gráfica. Tive algumas premissas pra definir o tamanho das cartas, por exemplo, trabalhei no limite do aceitável para o tamanho das fontes (a exceção é o link para a diretriz completa, mas acabei deixando pequena por ter o QRCode como opção)... falando do QRCode, pesquisando percebi que um tamanho mínimo aceitável para não ocorrer erros de leitura era um quadro de 2x2cm, então eu o deixei exatamente neste tamanho...

Enfim, se tiver alguma sugestão de formatação para as cartas eu aceito também. Sinta-se a vontade pra enviar um pull request com modificações... ;)

De qualquer forma, vou tentar separar um tempinho pra ajustar algumas coisas, incluindo algumas instruções para impressões como sugeriu... 

Obrigado!
