### ISSUE TITLE
Versão de acessibilidade toolkit no notion

### ISSUE THREAD

**Issue by filipecancio** [acessibilidade/toolkit#3]
Oi, eu precisei revisar as questões de WCAG na empresa onde eu trabalho e encontrei esse projeto, que achei maravilhoso, nessa eu aproveitei para montar um modelo semelhante no notion, para facilitar a utilização no trabalho. 
Segue o link: https://www.notion.so/Acessibilidade-Tolkit-a5b97315d5c44ad6991357f7c74f3658

**Comment by msales78** [comment]
Olá @filipecancio desculpe a demora no retorno, mas só consegui ver o seu material agora. Achei sensacional... obrigado por publicar esse material no Notion também... 👍 

Vou atualizar o Read.me com o link de sua versão... :)
